### ISSUE TITLE
Cant combine two strings (two word) into one phrase 

### ISSUE THREAD

**Issue by abbayosua** [abbayosua/learnJS#1]
https://github.com/abbayosua/learnJS/blob/2d13aa6bfdb005171394f860099a4381fcdb21d9/modified%20number/index.js#L19

**Comment by mhaidarhanif** [comment]
Use backtick 

```js
phrase = `string ${variable}`
```

**Comment by abbayosua** [comment]
![screenshot from 2018-07-20 14-57-37](https://user-images.githubusercontent.com/37859571/42990600-4c5cdf56-8c2d-11e8-889a-c48c4f8cce95.png)

**Comment by abbayosua** [comment]
have been using backtick
